formsort/oss

packages/eslint-config/index.js

we just sort imports according to groups, this PR enables sorting within groups ignoring case

eslint config: import alphabetize and ignore case

---

packages/react-embed/README.md

Update links in the readme of the react-embed library. These should lead to different sections of the readme of the web-embed library, but currently lead to a github 404 page.

update links in react-embed readme

---

packages/constants/package-lock.json
packages/custom-question-api/package-lock.json
packages/eslint-config/package-lock.json
packages/react-embed/package-lock.json
packages/web-embed-api/package-lock.json

- This PR includes changes to each project's `package-lock.json` resulting from running `npm run bootsrap` at the root of the repo.
- For 4 out of 5 lock files the changes are to the project itself (denoted via `""`) - the version in the lock file simply updated to match the version of the same project in `package.json`. See more details in the [official docs](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#packages).
- For the remaining lock file - `web-embed-api/package-lock.json` -  the changes seem to step from the `lockfileVersion` being updated from `1` to `2`. The would be the case when transition to npm v7 from a previous version, and includes backward compatibility. See more details in the [official docs](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-j …

Rerun bootstrap

---

packages/react-embed/src/index.tsx

Since users of Formsort can define custom environments, we allow passing any string for the `formSortEnv` prop in react-embed. This PR updates the prop, and defines a custom type to preserve the auto-complete for the default environments.
Intellisense for default environments:
Other values are allowed:

React-embed: Allow passing any string for `formsortEnv`

---

packages/constants/package-lock.json

- Running `lerna boostrap` resulted in the version of `@formsort/constants` to be updated within its own `package-lock.json `. This aligns with the version assigned in [constants/package.json](https://github.com/formsort/oss/blob/master/packages/constants/package.json#L3) - updated in PR [Add responder_user_id to constants](https://github.com/formsort/oss/commit/d5befd5c7837003dea1775631a9f814bc36a15cd)

re-boostrap - constants package version in lockfile

---

packages/web-embed-api/src/index.ts
packages/web-embed-api/src/interfaces.d.ts
packages/web-embed-api/src/typeGuards.test.ts
packages/web-embed-api/src/typeGuards.ts

This PR updates the web-embed package:
- Update interface types for events
- Add and use basic type guards to determine window message event type

Refactor and update web-embed message types 

---

packages/react-embed/jestconfig.json
packages/react-embed/package-lock.json
packages/react-embed/package.json
packages/web-embed-api/jest.config.js
packages/web-embed-api/package-lock.json
packages/web-embed-api/package.json

For both web-embed and react-embed packages:
- Update version of `jest` to 27.1.0, `ts-jest` to 27.0.5, and `@types/jest` to `27.0.1`.
- In the jest config file, set the [testEnvironment](https://jestjs.io/docs/configuration#testenvironment-string) to "jsdom". For the current version of jest, the default test environment is "node". We need to set the test environment to "jsdom" in order to test in a simulated browser environment, so that we can e.g. mock the global window object.

Update jest and related packages in web-embed and react-embed

---

packages/web-embed-api/examples/web-components/lit/.gitignore
packages/web-embed-api/examples/web-components/lit/README.md
packages/web-embed-api/examples/web-components/lit/index.html
packages/web-embed-api/examples/web-components/lit/index.ts
packages/web-embed-api/examples/web-components/lit/package-lock.json
packages/web-embed-api/examples/web-components/lit/package.json
packages/web-embed-api/examples/web-components/lit/tsconfig.json

- Create an `examples` subfolder in the `web-embed` folder
- Add an example using a [web component](https://developer.mozilla.org/en-US/docs/Web/Web_Components) created with  [lit](https://lit.dev/).
- The example embeds a flow within a web page (client, flow, and variant name provided via `.env` file), registers listeners for all event types (analytics events and redirect event), and logs all events with their payloads onto the page.

Add example project for web-embed using web components

---

packages/react-embed/package.json

Allow react v17 as peer-dependency for react-embed, so that projects using v17 can use the package.

react-embed: allow react v17 as peer-dependency

---

packages/web-embed-api/CHANGELOG.md
packages/web-embed-api/README.md
packages/web-embed-api/src/index.ts

The `customUrl` type annotation wasn't actually implemented, so it can
be removed

Add CHANGELOG and remove extraneous type

---

packages/web-embed-api/src/index.test.ts
packages/web-embed-api/src/index.ts
packages/web-embed-api/src/interfaces.ts
packages/web-embed-api/src/utils.ts

- Currently `embed.addEventListener` *replaces* the listener registered for that event type.
- Update `eventListeners` to be `eventListenersArrayMap`, so that it contains an array of listeners for each event type.
- Update  `embed.addEventListener`, so that it adds the event listener to the list of listeners registered for that event type.
- Add a `removeEventListener` method that, given an event name and a listener, removes the listener from the the list of listeners registered for that event type.

Update web-embed addEventListener to have appending behavior

---

.github/workflows/node.js.yml
packages/react-embed/src/__tests__/EmbedFlow.test.tsx

- Currently our github workflow is set to only run the tests for the `web-embed-api` package.
- This PR updates the workflow to also run the tests for the `react-embed` and `constants` packages.
- The PR also fixes a typescript error in the tests for `react-embed`.

run tests in ci for react-embed and constants

---

packages/react-embed/example/event-log/README.md
packages/react-embed/example/event-log/package.json

- remove old parcel version. The package name was `parcel-bundler` and the one for the new version is `parcel`.
- Use only `npm` in the example for consistency.

cleanup react-embed example

---

packages/custom-question-api/README.md
packages/custom-question-api/src/index.ts

- update the type definition of  `setQuestionSize` to allow passing string values for height and width. This is supported in the flow.

custom-question-api: allow setting question size with string value

---

packages/constants/src/web-embed-message/index.ts
packages/web-embed-api/README.md
packages/web-embed-api/src/index.ts
packages/web-embed-api/src/typeGuards.ts

Add the ability to listen to `unauthorized` events in the Web Embed API.

add callback for unauthorized message

---

.github/workflows/release.yml
.vscode/settings.json

Adds a GitHub workflow that can be triggered from the UI, or CLI to publish a package automatically from the CI. The workflow uses the `release` environment which contains the `NPM_TOKEN` secret for the `formsort-release` account and is protected by environment rules: https://github.com/formsort/oss/settings/environments/448906217/edit
Finishes off APP-12

ci: Add publishing through GitHub Actions

---

packages/react-embed/package.json
packages/web-embed-api/examples/authenticated-flow/package.json
packages/web-embed-api/examples/formsort-embed-example-lit/package.json
packages/web-embed-api/package.json
packages/web-embed-api/src/index.test.ts
packages/web-embed-api/src/index.ts

Implements [FLOW-154](https://formsort.atlassian.net/browse/FLOW-154)
Remove the unnecessary Client label from the default Flow Url. Both URLs work, but the subdomain already defines the client label to be used, so it is simpler.

Remove Client label from the default Flow Url

---

packages/custom-question-api/examples/react/package.json
packages/react-embed/examples/event-log/package.json
packages/react-embed/examples/event-log/src/index.tsx
packages/react-embed/examples/simple/package.json
packages/react-embed/package.json
packages/react-embed/src/__tests__/EmbedFlow.test.tsx
packages/react-embed/src/index.tsx
packages/web-embed-api/README.md
packages/web-embed-api/examples/authenticated-flow/package.json
packages/web-embed-api/examples/formsort-embed-example-lit/package.json
packages/web-embed-api/package.json
packages/web-embed-api/src/index.ts
yarn.lock

Fixes #72 
In React Strict mode, the embed renders twice. This PR includes an `unloadFlow` on the Web Embed interface and uses it to remove the effects of double rendering.

Issue 72 - Support React 18

---

package.json
yarn.lock

Fixes vulnerability [CVE-2022-46175](https://avd.aquasec.com/nvd/2022/cve-2022-46175/) by resolving `json5` to version `2.2.3`.
Uses selective dependency/version resolutions: https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/.

Fix CVE-2022-46175

---

packages/constants/.craft.yml

Fixes the `@formsort/constants` release error about missing artifacts.
See examples [here](https://github.com/formsort/oss/actions/runs/3875355992/jobs/6607776596#step:4:218) and [here](https://github.com/formsort/oss/actions/runs/3833292857/jobs/6524599594#step:4:209).

fix constants package artifact search regexp

---

packages/custom-question-api/package.json
packages/web-embed-api/package.json
yarn.lock

Upgrade `@formsort/constants` dependency versions in:
- web-embed-api
- custom-question-api
Steps to follow up on after this PR is merged:
- Release new version of web-embed-api (as a patch)
- Upgrade web-embed-api dependency versions (ex. in react-embed)
- Release new version of custom-question-api (as a patch)
- Upgrade custom-question-api dependency versions (ex. in examples/)

Upgrade `constants` package dependency versions

---

packages/react-embed/package.json
packages/web-embed-api/examples/authenticated-flow/package.json
packages/web-embed-api/examples/formsort-embed-example-lit/package.json
yarn.lock

Follow up to https://github.com/formsort/oss/pull/89. Upgrades dependency version for `@formsort/web-embed-api`.
After this PR is merged:
- Release a new version of `react-embed` library, as a patch
- Upgrade dependency versions of `react-embed` to the latest patch

Upgrade dependency version for `web-embed-api`

---

packages/react-embed/examples/event-log/package.json
packages/react-embed/examples/simple/package.json
yarn.lock

Follow up to https://github.com/formsort/oss/pull/91. Upgrades dependency version for `@formsort/react-embed`.
This wraps up the package version upgrade saga 🥳

Upgrade dependency version for `react-embed`

---

packages/custom-question-api/README.md
packages/custom-question-api/src/index.ts

Uses the approach prototyped https://github.com/formsort/custom-question-examples/blob/main/auto-height/index.html

Add a setAutoHeight method to allow automatic sync of question height

---

packages/custom-question-api/src/index.ts

By separating an inner method we can warn users who manually call setQuestionSize but not also warn when the message is being sent by the autoheight logic

Don't warn about using autoHeight when autoHeight is enabled

---

packages/constants/src/analytics-event-type/index.ts

This will be used on the flow side to allow users of the embed to subscribe to changes to the responder state with the same frequency as saveAnswers() is called, so that they can implement answer saving / loading on their own.

Add a ResponderStateUpdated analytics event type

---

.github/workflows/build.yml
packages/embed-messaging-manager/.craft.yml
packages/embed-messaging-manager/.prettierrc
packages/embed-messaging-manager/LICENSE
packages/embed-messaging-manager/README.md
packages/embed-messaging-manager/package.json
packages/embed-messaging-manager/src/index.ts
packages/embed-messaging-manager/src/typeGuards.test.ts
packages/embed-messaging-manager/src/typeGuards.ts
packages/embed-messaging-manager/src/utils.ts
packages/embed-messaging-manager/tsconfig.build.json
packages/embed-messaging-manager/tsconfig.json
packages/web-embed-api/src/index.ts
packages/web-embed-api/tsconfig.build.json
yarn.lock

Copies [EmbedMessagingManager](<https://github.com/formsort/oss/blob/master/packages/web-embed-api/src/EmbedMessagingManager.ts>) to a package.
Follow-up #106
After publishing this package, we're gonna replace  the class with this package and use this package to build a React native embed library.

FLOW-606: make new embed messaging class a package

---

packages/embed-messaging-manager/package.json

in #111, `constants` and `embed-messaging-manager` were updated.
So we need to cut releases for dependent packages step by step.

Prepare embed-messaging-manager for release

---

packages/web-embed-api/src/index.ts

Only remove the child if iframe still contains contentDocument. If user clicks on the close hyperlink in the embed, contentDocument will be removed.
should fix: #128 
or some fix along the line of this

fix: removing missing childNode error
